### ISSUE TITLE
好的。

### ISSUE THREAD

**Issue by dalton-chiou** [rp-hello/luci-app-v2ray#1]
如题。

**Comment by rp-hello** [comment]
1. 这个项目的原始源代码是 https://github.com/kuoruan/luci-app-v2ray ，之前提过pr，但是作者没有合并。看起来3年没有更新了，所以我就没有使用fork的选项。
2. 这个项目也没有想着抄，所有的历史提交都保留，可以从其中查到原始的记录
3. 在readme上，会添加上原始链接。

**Comment by rp-hello** [comment]
在readme中已经添加了fork说明。<https://github.com/rp-hello/luci-app-v2ray/commit/45a08ad4f5651e74a1d14bd8280d4c2157148411>
